option('cactlib', type: 'string', value: '../CactLibc-x86_32',
  description: 'CactLibc project root, relative to this repo or absolute')

option('lr_sbin', type: 'string', value: '../LocalRepoCactOS-x86_32/lib/sbin',
  description: 'staging /sbin directory used by the stage target, relative or absolute')

option('lr_lib', type: 'string', value: '../LocalRepoCactOS-x86_32/lib',
  description: 'staging /lib directory used by the stage target, relative or absolute')
